---
title: "Introduction to the forecastLM package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to the forecastLM package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=8
)
```



The forecastLM package provides a framework for forecasting regular time series data with a linear regression model. This vignette introduces the basic forecasting process with the package. The following vignettes cover advanced functionalities of the package.

Basic forecasting

```{r setup}
library(forecastLM)

data("ny_gas")
```


```{r}
head(ny_gas)

class(ny_gas)
```





```{r fig.width=8}
library(TSstudio)

ts_plot(ny_gas,
        title = "The New York Natural Gas Residential Monthly Consumptio",
        Ytitle = "Million Cubic Feet",
        Xtitle = "Source: US Energy Information Administration (Jan 2020)")
```




```{r}
md1 <- trainLM(input = ny_gas, 
              y = "y",
              seasonal = "month",
              trend = list(linear = TRUE))
```


```{r}
names(md1)
```

```{r}
summary(md1$model)
```

```{r}
plot_fit(md1)
```

```{r fig.height=8, fig.width=8}
plot_res(md1)
```


```{r}

events <- list(outlier = c(as.Date("2015-01-01"), as.Date("2015-02-01"), as.Date("2018-01-01"), as.Date("2019-01-01")))
```



```{r}
md2 <- trainLM(input = ny_gas, 
              y = "y",
              seasonal = "month",
              trend = list(linear = TRUE),
              events = events)
```




```{r fig.height=8, fig.width=8}
plot_res(md2)
```


```{r}
md3 <- trainLM(input = ny_gas, 
              y = "y",
              seasonal = "month",
              trend = list(linear = TRUE),
              events = events,
              lags = c(1,12))
```




```{r fig.height=8, fig.width=8}
plot_res(md3)
```






```{r}
fc3 <- forecastLM(md3, h = 60)
```






```{r}
plot_fc(fc3)
```



